name: Run Bot From Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Неубиваемое скачивание релиза через встроенный GitHub CLI
    - name: Download Release Asset
      run: |
        gh release download --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Unzip project archive
      run: |
        unzip -o *.zip
        rm *.zip

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt не найден"
        fi

    - name: Run AI Bot
      timeout-minutes: 300
      run: python main.py
