name: Run Bot From Release

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download Archive
      run: |
        curl -L \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/octet-stream" \
          -o project.zip \
          "https://api.github.com/repos/${{ github.repository }}/releases/assets/$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest | jq '.assets[0].id')"

    - name: Unzip project archive
      run: |
        unzip -o project.zip
        rm project.zip

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt не найден"
        fi

    - name: Run AI Bot
      timeout-minutes: 300
      run: python main.py
